### ISSUE TITLE
Duda sobre position

### ISSUE THREAD

**Issue by RominaPanzardo** [RominaPanzardo/tp2-portfolio#1]
# duda sobre position #
Estuve probando hacer este recuadro con el diseño planteado en figma. Logré que las estrellas se superpongan usando position relative en el div padre  y "position absolute" en las estrellas en si mismas. 

En el inspector empecé a probar cuantos pixeles tendría que moverse y que el numero de px sea tan grande me hace dudar si está bien.
Habría otra forma de resolverlo o así como lo resolví estaría bien?? Me genera dudas también como respondería esto en el responsive.

### dejo capturas de como lo hice: ###
![cartel-estrellas-position](https://github.com/RominaPanzardo/tp2-portfolio/assets/164932077/e500cc6c-54c0-45cd-817b-f8f3a86bcdf5)

### en su posición original sin los px las estrellas aparecen así: ###
![cartel-estrellas-position-2](https://github.com/RominaPanzardo/tp2-portfolio/assets/164932077/978bd11d-1d5d-48e8-af1b-39bc75441519)

**Comment by aime-fdg** [comment]
Si es un marco para una foto directamente exportá la foto con el marco y listo porque sino va a ser muy complejo. Sino se me ocurre que podés hacerlo con align-self de flexbox al elemento particular y algún número negativo para que se superponga en el límite del border, capaz haya que agregar z-index

**Comment by aime-fdg** [comment]
Ahí me puse a ver y cuando se achica queda un poco raro y con scroll
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/f6aabc8d-5da5-4040-aee5-a6fffb436c8f)

Entiendo el problema de los números que son muy grandes y hay algunos números fijos que están dudosos, la solución que encontré es esta:
En primer lugar le puse width y height al article y cambié el orden de las estrellas con la idea de que hagan un sánguche de la foto
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/f487b8cd-d828-4ccb-a783-795e0752f935)

volé el position del recuadro y le puse flex, así podemos aplicar un align-self
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/70dd25ec-c667-4ba2-80fb-e24b63d1c6c9)

Los elementos que deberían tener position son las estrellitas, la de arriba va a tener aling-self a la derecha así es más fácil que los números de position sean más chicos y que estén relativos a su caja padre
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/9670063b-6bfc-489e-a283-b39ad23b758c)

y a la otra estrella lo mismo
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/c61e656a-f34c-4c58-afe4-23d931089059)

También le hice un par de ajustes a la foto, no me acuerdo específicamente cuales pero te dejo la captura
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/5f78deb6-2338-4bb7-b2f2-55a3efad10f7)

Con esto debería quedar así:
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/8f63edb9-5398-480b-bc97-43c56bc08ffa)
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/46706df0-8787-4f63-bf27-8d1b75071a43)

Hay que arreglar un par de cosas más cosas para que quede más prolijo pero solucionamos el problema principal

**Comment by aime-fdg** [comment]
Investigué un poquito más el por qué genera el espacio entre el título y el div y podés utilizar la propiedad translate que es parecida a position pero tiene mejores resultados
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/81a0f7e7-ddbb-4eda-967f-d5c1984b3ffd)
![image](https://github.com/RominaPanzardo/tp2-portfolio/assets/74267187/68f0405a-e1f6-4f95-9973-aba22ad1fa12)
